### ISSUE TITLE
Slack?

### ISSUE THREAD

**Issue by nelsonic** [tcm-labs/workflow#5]
The project team is using Slack for _ephemeral_ communication.
but equally many _story-related_ discussions are being had in Slack 

## Todo

+ [ ] How do I get access to Slack?
+ [ ] What should I use Slack for?
+ [ ] What should I _not_ use Slack for?

**Comment by nelsonic** [comment]
In the following example we have two ways of using Slack to "_communicate_"
both of these messages are drawing attention to a Story on GitHub:
![valuing-peoples-time-vs-wasting-time](https://user-images.githubusercontent.com/194400/32186564-4e8cac00-bd9a-11e7-8d9f-7bf469fd3d1b.png)

The ***first*** is ***targeted*** to **_specific_ person** and includes the **link** so the person can click and go _directly_ to the issue without any effort. (_Yet other members of the team who were on the call/discussion at the time can effortlessly see it too._)

The ***second*** message is ***vague*** (_**who** is it for?!_) and ***forces everyone*** to _copy-paste_ the issue number or **_manually_ type** it into their browser in order to navigate the to the story.

Which do _you_ think is the most _effective_ way to _communicate_?

This may appear to be "nitpicking" but to consider the following:
This person has referred to "Story 76" (_without a link_) which has forced other people to perform additional actions in in order to view the story. i.e. it has **_created_ more work** for (_at least 5_) **other people** (_including the **scarcest** members of the team: Front-end Developers!_)
If the person had _instead_ linked _directly_ to the story e.g: https://github.com/tcm-labs/tcm-payg-app/issues/76 it would have saved _everyone **`else`**_ time.
Sure, it's "_**only** a **couple** of **seconds**_", but it's the _principal_ that matters. 
This person is a "***repeat offender***", continuously wasting other people's time through their laziness.

**Comment by nelsonic** [comment]
The _lazy_ behaviour continues:
![repeat-offender](https://user-images.githubusercontent.com/194400/32226486-8f7ff8d8-be40-11e7-945b-25c658daad32.png)

**Comment by nelsonic** [comment]
Most "slack integrations" are _noise_:
![slack-waffle-integration-is-useless](https://user-images.githubusercontent.com/194400/32241658-ab956544-be68-11e7-9164-bb752e8f2311.png)
_Everyone_ in the team (25) people will get _exactly_ the same notification _regardless_ of it's _relevance_ to them. slack (_when used ineffectively_) is a _constant_ source of interruption.
